import assert from 'node:assert/strict'
import { mkdirSync,writeFileSync } from 'node:fs'
import { createInitialState,trainingCost } from '../../src/domain/systems/demo.ts'
import { MISSIONS } from '../../src/content/progression.ts'
import { stageConfig } from '../../src/content/demo.ts'
const {chromium}=await import(process.env.TASK_PLAYWRIGHT_MODULE || 'playwright')
const browser=await chromium.launch({headless:process.env.TASK_HEADED!=='1',executablePath:process.env.TASK_BROWSER_EXECUTABLE || undefined,args:['--disable-dev-shm-usage']})
const context=await browser.newContext({viewport:{width:1370,height:1050}}),page=await context.newPage()
const errors=[],checks=[]
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'||m.type()==='warning')errors.push(m.text())})
const root='artifacts/browser-demo';mkdirSync(root,{recursive:true})
const url=(process.env.TASK_GAME_URL || 'http://127.0.0.1:5174/')+'?test'
const snapshot=()=>page.evaluate(()=>window.__demo.snapshot())
const restore=s=>{for(const m of MISSIONS)if(s.kills>=m.kills&&s.cleared>=m.cleared)s.quests.push('mission-'+m.id);if(s.kills>=5)s.quests.push('opening-boss-triggered');return page.evaluate(s=>window.__demo.restore(s),s)}
const fresh=()=>page.evaluate(()=>window.__demo.fresh())
const time=ms=>page.evaluate(ms=>window.advanceTime(ms),ms)
const click=()=>page.locator('canvas').click({position:{x:280,y:240}})
function fixture(){return createInitialState(Date.now())}
async function test(name,fn){await fn();checks.push(name);console.log('PASS '+name)}
try{
 await page.goto(url);await page.waitForFunction(()=>window.__demo&&document.querySelector('canvas'))
 await test('5th kill lights manual button inside game; approach and contact retreat',async()=>{await fresh();assert.equal(await page.locator('[data-panel]').count(),1);let state=await snapshot();for(let n=0;n<80&&state.kills<5;n++){await click();await time(200);state=await snapshot()}assert.equal(state.kills,5);assert.equal(state.mode,'farm');assert.equal(state.coins,328);assert(await page.locator('[data-action="challenge"]').isEnabled());assert(await page.locator('.boss-ready-notice').isVisible());await page.screenshot({path:root+'/boss-ready.png'});await page.locator('[data-action="challenge"]').click();state=await snapshot();assert.equal(state.mode,'boss');assert.equal(state.bossTime,12);assert(state.bossIntro>0);assert.equal(await page.locator('[data-panel="skills"]').count(),0);await time(1900);await page.waitForTimeout(200);await page.screenshot({path:root+'/boss-distant.png',fullPage:true});const hp=(await snapshot()).hp;await time(8500);await page.waitForTimeout(200);assert((await snapshot()).bossTime<4);assert.equal((await snapshot()).hp,hp);await page.screenshot({path:root+'/boss-near.png',fullPage:true});await time(4000);assert.equal((await snapshot()).mode,'farm');assert.equal((await snapshot()).cleared,0);assert((await snapshot()).lastResult.includes('冲到了面前'));assert.equal((await snapshot()).quests.filter(x=>x==='mission-entry-5').length,1)})
 await test('fresh actual clicks kill and training purchase changes attack',async()=>{await fresh();for(let n=0;n<5;n++){await click();await time(250)}await time(700);const s=await snapshot();assert.equal(s.kills,1);assert.equal(s.coins,136);assert.equal(s.scrap,1);for(let n=0;n<80&&(await snapshot()).kills<5;n++){await click();await time(200)}assert.equal((await snapshot()).mode,'farm');await page.locator('[data-action="challenge"]').click();await time(1900);for(let n=0;n<60&&(await snapshot()).cleared<1;n++){await click();await time(200)}assert.equal((await snapshot()).cleared,1);await page.screenshot({path:root+'/first-victory.png'});await page.getByRole('button',{name:'战斗详情与任务'}).click();const before=await snapshot();assert(before.coins>=trainingCost(before));await page.locator('[data-action="train"]').click();assert.equal((await snapshot()).training,2);await page.screenshot({path:root+'/combat.png',fullPage:true})})
 await test('hold mouse/space and B burst; fullscreen toggle',async()=>{await fresh();const box=await page.locator('canvas').boundingBox();await page.mouse.move(box.x+280,box.y+240);await page.mouse.down();for(let n=0;n<10;n++){await time(220);await page.waitForTimeout(35)}await page.mouse.up();assert((await snapshot()).shotSerial>=6);const mouseShots=(await snapshot()).shotSerial;await page.keyboard.down('Space');for(let n=0;n<8;n++){await time(250);await page.waitForTimeout(35)}await page.keyboard.up('Space');const before=(await snapshot()).shotSerial;assert(before>mouseShots);const open=fixture();open.kills=120;open.cleared=3;open.stage=4;await restore(open);await page.keyboard.press('b',{delay:80});assert((await snapshot()).burstUntil>(await snapshot()).clockMs);await page.bringToFront();await page.waitForTimeout(300);await page.keyboard.press('f',{delay:80});await page.waitForFunction(()=>!!document.fullscreenElement,{},{timeout:3000});await page.waitForTimeout(300);await page.keyboard.press('f',{delay:80});await page.waitForFunction(()=>!document.fullscreenElement,{},{timeout:3000})})
 await test('boss timeout/retreat and actual first-clear route progression',async()=>{const s=fixture();s.kills=5;s.stageKills['1']=5;await restore(s);await page.locator('[data-action="challenge"]').click();assert.equal((await snapshot()).mode,'boss');await time(26000);assert.equal((await snapshot()).cleared,0);assert.equal((await snapshot()).coins,120);s.training=80;await restore(s);await page.locator('[data-action="challenge"]').click();await time(2000);await click();const won=await snapshot();assert.equal(won.cleared,1);assert.equal(won.stage,2)})
 await test('market buy, proficiency lock, equip and strengthen an unselected gun',async()=>{const s=fixture();s.cleared=8;s.stage=9;s.kills=10000;s.coins=1e7;s.scrap=10000;s.proficiency={pistol:100,rifle:0,shotgun:0};await restore(s);await page.locator('[data-panel="market"]').click();await page.locator('[data-buy="famas"]').click();await page.locator('[data-buy="carbine"]').click();await page.locator('[data-panel="inventory"]').click();assert(await page.locator('[data-equip="famas"]').isDisabled());await page.locator('[data-enhance="famas"]').click();assert.equal((await snapshot()).enhancements.famas,1);assert.equal((await snapshot()).weapon,'glock');await page.locator('[data-equip="carbine"]').click();assert.equal((await snapshot()).weapon,'carbine');await page.screenshot({path:root+'/inventory.png',fullPage:true})})
 await test('handbook/companion/research/achievements through UI',async()=>{const s=fixture();s.cleared=12;s.stage=13;s.cans=200;s.researchPoints=30;s.fragments=[2,2,2];s.kills=12000;await restore(s);await page.locator('[data-panel="skills"]').click();await page.getByRole('button',{name:'学习 · 1 套',exact:true}).first().click();assert.equal((await snapshot()).manuals[0],1);await page.locator('[data-panel="pets"]').click();await page.getByRole('button',{name:'5 罐头 · 升级',exact:true}).nth(1).click();await page.getByRole('button',{name:'携带',exact:true}).nth(1).click();assert.equal((await snapshot()).pet,1);await page.locator('[data-panel="research"]').click();await page.getByRole('button',{name:'3 研究点',exact:true}).first().click();assert.equal((await snapshot()).research.power,1);await page.locator('[data-panel="map"]').click();await page.getByRole('button',{name:'领取',exact:true}).first().click();assert((await snapshot()).claimedAchievements.length===1);await page.screenshot({path:root+'/map.png',fullPage:true})})
 await test('plant boss rendered with countdown; success ending at24',async()=>{const s=fixture();s.cleared=7;s.stage=8;s.kills=1000;s.stageKills['8']=stageConfig(8).target;s.training=100;await restore(s);await page.locator('[data-panel="combat"]').click();await page.locator('[data-action="challenge"]').click();await time(2000);await page.waitForTimeout(200);await page.screenshot({path:root+'/plant-boss.png',fullPage:true});await click();assert.equal((await snapshot()).cleared,8);const end=fixture();end.cleared=23;end.stage=24;end.kills=30000;end.stageKills['24']=stageConfig(24).target;end.training=120;end.owned=['glock','rail'];end.weapon='rail';end.proficiency.rifle=1000;await restore(end);await page.locator('[data-action="challenge"]').click();await time(2000);await click();assert.equal((await snapshot()).cleared,24);await page.screenshot({path:root+'/ending.png',fullPage:true})})
 await test('ads cancel no reward; complete cooldown and no duplicate; typing modal blocks shots',async()=>{const s=fixture();s.cleared=3;s.stage=4;s.kills=300;await restore(s);await page.getByRole('button',{name:'无线电补给',exact:true}).click();await page.locator('[data-ad="coins"]').click();assert.equal((await snapshot()).coins,120);await page.locator('[data-action="ad-cancel"]').click();assert.equal((await snapshot()).ads.total,0);await page.locator('[data-ad="coins"]').click();assert(await page.locator('[data-action="ad-complete"]').isDisabled());await page.waitForTimeout(3300);await page.locator('[data-action="ad-complete"]').click();assert((await snapshot()).coins>120);assert.equal((await snapshot()).ads.total,1);assert(await page.locator('[data-ad="coins"]').isDisabled());await page.screenshot({path:root+'/supplies.png',fullPage:true});await page.getByRole('button',{name:'关闭',exact:true}).click();await page.getByRole('button',{name:'设置与存档'}).click();const shots=(await snapshot()).shotSerial;await page.getByRole('textbox',{name:'存档 JSON 文本'}).fill('abc ');await page.keyboard.press('Space');const open=fixture();open.kills=120;open.cleared=3;open.stage=4;await restore(open);await page.keyboard.press('b',{delay:80});assert.equal((await snapshot()).shotSerial,shots);await page.getByRole('button',{name:'关闭',exact:true}).click()})
 await test('offline base claim, optional extra once, saved reload and corrupt-save preservation',async()=>{const s=fixture();s.cleared=3;s.stage=4;s.kills=300;s.lastSaveMs=Date.now()-3600000;await page.addInitScript(()=>{const pending=localStorage.getItem('zombie-clicker-idle:save:v1:test:qa-offline');if(pending){localStorage.setItem('zombie-clicker-idle:save:v1:test',pending);localStorage.removeItem('zombie-clicker-idle:save:v1:test:qa-offline')}});await page.evaluate(s=>localStorage.setItem('zombie-clicker-idle:save:v1:test:qa-offline',JSON.stringify(s)),s);await page.reload();await page.waitForFunction(()=>window.__demo);const loaded=await snapshot();assert(loaded.offline.coins>0);await page.locator('[data-action="offline"]').click();assert((await snapshot()).coins>120);await page.getByRole('button',{name:'无线电补给',exact:true}).click();await page.locator('[data-ad="offline"]').click();await page.waitForTimeout(3300);await page.locator('[data-action="ad-complete"]').click();assert((await snapshot()).offline.bonusClaimed);assert(await page.locator('[data-ad="offline"]').isDisabled());await page.getByRole('button',{name:'关闭',exact:true}).click();await page.evaluate(()=>window.__demo.save());const coins=(await snapshot()).coins;await page.reload();await page.waitForFunction(()=>window.__demo);assert.equal((await snapshot()).coins,coins);const corruptPage=await context.newPage();await corruptPage.addInitScript(()=>localStorage.setItem('zombie-clicker-idle:save:v1:test','{broken'));await corruptPage.goto(url);await corruptPage.waitForFunction(()=>window.__demo);assert(await corruptPage.getByRole('alert').count());assert.equal(await corruptPage.evaluate(()=>localStorage.getItem('zombie-clicker-idle:save:v1:test')),'{broken');await corruptPage.close();await fresh()})
 await test('invalid import keeps current state; downloaded/export text and confirmed reset',async()=>{await page.getByRole('button',{name:'设置与存档'}).click();await page.getByRole('button',{name:'生成备份',exact:true}).click();const text=await page.getByRole('textbox',{name:'存档 JSON 文本'}).inputValue();assert.equal(JSON.parse(text).schemaVersion,3);await page.getByRole('textbox',{name:'存档 JSON 文本'}).fill('{"schemaVersion":2}');await page.getByRole('button',{name:'导入文本',exact:true}).click();assert.equal((await snapshot()).training,1);await page.getByRole('textbox',{name:'存档 JSON 文本'}).fill(text);await page.getByRole('button',{name:'导入文本',exact:true}).click();assert((await page.getByRole('status').innerText()).includes('已导入'));await page.getByRole('button',{name:'开始新游戏',exact:true}).click();await page.getByRole('button',{name:'确认清空并开始新游戏',exact:true}).click();assert.equal((await snapshot()).coins,120);await page.getByRole('button',{name:'关闭',exact:true}).click()})
 await test('mobile fits, fixed navigation changes panel and returns to battle',async()=>{await page.setViewportSize({width:390,height:844});await fresh();await page.waitForTimeout(250);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:root+'/mobile-combat.png',fullPage:true});assert.equal(await page.locator('[data-panel="inventory"]').count(),0);const open=fixture();open.kills=25;open.cleared=1;open.stage=2;await restore(open);await page.locator('[data-panel="inventory"]').click();await page.waitForTimeout(350);assert.equal((await snapshot()).selectedPanel,'inventory');await page.screenshot({path:root+'/mobile-inventory.png',fullPage:true});await page.locator('[data-panel="combat"]').click();assert.equal((await snapshot()).selectedPanel,'combat');await page.setViewportSize({width:1370,height:1050});await fresh();await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:root+'/desktop.png',fullPage:true})})
 await test('all visible controls contained in game surface; menus block shooting',async()=>{const bounds=await page.locator('.workspace').boundingBox();for(const el of await page.locator('button:visible').all()){const b=await el.boundingBox();assert(b.x>=bounds.x-1&&b.y>=bounds.y-1&&b.x+b.width<=bounds.x+bounds.width+1&&b.y+b.height<=bounds.y+bounds.height+1)}await page.getByRole('button',{name:'战斗详情与任务'}).click();const count=(await snapshot()).shotSerial;await page.keyboard.press('Space');assert.equal((await snapshot()).shotSerial,count);await page.getByRole('button',{name:'返回战斗',exact:true}).click();assert.equal(await page.locator('.panel-content').count(),0)})
 assert.deepEqual(errors,[])
 writeFileSync('artifacts/browser-checks.json',JSON.stringify({passed:checks.length,checks,errors},null,2))
}catch(error){writeFileSync('artifacts/browser-failure.json',JSON.stringify({checks,errors,state:await snapshot(),fullscreen:await page.evaluate(()=>({active:!!document.fullscreenElement,enabled:document.fullscreenEnabled,focused:document.hasFocus()})),error:String(error)},null,2));throw error}finally{await browser.close()}
