import assert from 'node:assert/strict'
import { writeFileSync,mkdirSync } from 'node:fs'
import { WEAPONS,stageConfig } from '../../src/content/demo.ts'
import * as P from '../../src/domain/systems/progression.ts'
import { MISSIONS } from '../../src/content/progression.ts'
import * as R from '../../src/domain/systems/demo.ts'
const results=[]
function test(name,fn){fn();results.push(name);console.log('PASS '+name)}
const now=Date.UTC(2026,8,30)
test('fresh-save manual kill gives one reward, no repeat on dead enemy',()=>{const s=R.createInitialState(now);s.hp=1;assert(R.shoot(s));assert.equal(s.kills,1);assert.equal(s.coins,136);assert(!R.shoot(s));assert.equal(s.kills,1);R.advance(s,.6);assert(s.hp>0)})
test('manual cooldown and 20-kill bounty plus 9-kill fragment drop',()=>{const s=R.createInitialState(now);s.training=80;s.cleared=1;s.quests=MISSIONS.map(m=>'mission-'+m.id).concat('opening-boss-triggered');for(let i=0;i<20;i++){assert(R.shoot(s));assert(!R.shoot(s));R.advance(s,.6)}assert.equal(s.kills,20);assert.equal(s.cans,1);assert.equal(s.coins,120+16*25);assert.deepEqual(s.fragments,[0,0,0]);assert.equal(s.proficiency.pistol,20)})
test('weapon purchase gated by first-clear and equip gated by proficiency',()=>{const s=R.createInitialState(now);s.coins=1e9;assert(!R.buyWeapon(s,'rail'));s.cleared=1;s.kills=25;assert(R.buyWeapon(s,'revolver'));assert(!R.buyWeapon(s,'revolver'));assert(!R.equip(s,'revolver'));s.proficiency.pistol=8;assert(R.equip(s,'revolver'));s.kills=60;s.cleared=2;s.scrap=15;assert(R.enhance(s,'glock'));assert.equal(s.enhancements.glock,1);assert.equal(s.weapon,'revolver');assert.equal(s.scrap,0)})
test('boss prerequisite, timeout and retreat preserve resources',()=>{const s=R.createInitialState(now);assert(!R.challenge(s));s.kills=5;s.stageKills['1']=5;assert(R.challenge(s));assert.equal(s.bossTime,stageConfig(1).bossSeconds);R.advance(s,26);assert.equal(s.cleared,0);assert.equal(s.mode,'farm');assert.equal(s.coins,120);assert(R.challenge(s));assert(R.retreat(s));assert.equal(s.mode,'farm');assert.equal(s.coins,120)})
test('boss first-clear only once; advance route unlocks auto at stage 3',()=>{const s=R.createInitialState(now);s.training=100;s.kills=300;s.autoEnabled=false;for(let n=1;n<=3;n++){s.stageKills[String(n)]=stageConfig(n).target;assert(R.challenge(s));R.advance(s,1.9);s.manualCooldown=0;assert(R.shoot(s));assert.equal(s.cleared,n);assert.equal(s.stage,n+1);R.advance(s,1)}assert(R.autoUnlocked(s));s.autoEnabled=true;const before=s.kills;R.advance(s,5);assert(s.kills>before);assert(R.chooseStage(s,1));assert(!R.challenge(s));assert(!R.chooseStage(s,5))})
test('enemy counter: shotgun swarm advantage, rifle armor penetration',()=>{const s=R.createInitialState(now);s.owned=WEAPONS.map(w=>w.id);s.weapon='sawed';s.enemyKind='swarm';assert.equal(R.adjustedDamage(s),96);s.enemyKind='armored';assert.equal(R.adjustedDamage(s),39);s.weapon='rail';assert.equal(R.adjustedDamage(s),1200)})
test('pets only carried effect, handbooks consume sets, research costs scale',()=>{const s=R.createInitialState(now);s.cleared=12;s.kills=10000;s.cans=100;s.fragments=[2,2,2];assert(R.upgradePet(s,0));assert(R.selectPet(s,0));assert.equal(R.lootMultiplier(s),1.04);assert(R.upgradePet(s,1));assert(R.selectPet(s,1));assert.equal(R.lootMultiplier(s),1);assert.equal(R.critChance(s),.055);assert(R.learnManual(s,1));assert.deepEqual(s.fragments,[1,1,1]);s.researchPoints=8;assert(R.upgradeResearch(s,'power'));assert(R.upgradeResearch(s,'power'));assert.equal(s.researchPoints,0);assert(!R.upgradeResearch(s,'power'))})
test('market repeated purchase blocked; refresh only restores material stock',()=>{const s=R.createInitialState(now);s.cleared=3;s.kills=300;s.coins=1e6;assert(R.buyMaterial(s,'cans'));assert(!R.buyMaterial(s,'cans'));assert.equal(s.cans,5);assert(R.refreshMarket(s));assert(R.buyMaterial(s,'cans'));assert.equal(s.cans,10);assert(!R.buyWeapon(s,'rail'))})
test('offline unlock, cap, no overwrite, base claim and additional reward once',()=>{let s=R.createInitialState(now);R.settleOffline(s,now+3600000);assert.equal(s.offline,null);s=R.createInitialState(now);s.cleared=3;s.kills=300;R.settleOffline(s,now+12*3600000);assert.equal(s.offline.seconds,7200);const coins=s.offline.coins;R.settleOffline(s,now+13*3600000);assert.equal(s.offline.coins,coins);assert(!R.completeDemoAd(s,'offline','no-base',true));assert(R.claimOffline(s));assert(!R.claimOffline(s));const base=s.coins;assert(R.completeDemoAd(s,'offline','additional',true));assert.equal(s.coins,base+coins);assert(!R.completeDemoAd(s,'offline','additional-2',true));assert.equal(s.coins,base+coins);s.autoEnabled=false;R.settleOffline(s,now+14*3600000);assert.equal(s.offline.coins,coins)})
test('cancelled ads no reward, receipts deduplicate, cooldown and daily quota',()=>{const s=R.createInitialState(now);s.cleared=3;s.kills=300;assert(!R.completeDemoAd(s,'coins','cancelled',false));assert.equal(s.ads.total,0);const coins=s.coins;assert(R.completeDemoAd(s,'coins','one',true));assert(s.coins>coins);assert(!R.completeDemoAd(s,'coins','one',true));assert(!R.completeDemoAd(s,'coins','cooldown',true));for(let i=2;i<=3;i++){s.clockMs+=301000;assert(R.completeDemoAd(s,'coins','receipt-'+i,true))}s.clockMs+=301000;assert(!R.completeDemoAd(s,'coins','over',true));s.clockMs+=86400000;assert(R.adAvailable(s,'coins'));assert(R.completeDemoAd(s,'coins','new-day',true));assert.equal(s.ads.total,1);assert(!R.completeDemoAd(s,'coins','one',true))})
test('global daily cap and auto-trial expire; permanent auto does not require ad',()=>{const s=R.createInitialState(now);s.cleared=3;s.kills=120;assert(R.completeDemoAd(s,'auto','trial',true));assert(R.autoUnlocked(s));s.clockMs+=601000;assert(!R.autoUnlocked(s));s.kills=300;assert(R.autoUnlocked(s));assert(!R.completeDemoAd(s,'auto','permanent',true));s.ads.total=12;assert(!R.adAvailable(s,'cans'))})
test('achievements once, burst 8s and 45s cooldown, boss health monotonic',()=>{const s=R.createInitialState(now);s.kills=100;assert(R.claimAchievement(s,'kills-100'));assert(!R.claimAchievement(s,'kills-100'));assert.equal(s.cans,8);assert(!R.burst(s));s.cleared=2;assert(R.burst(s));assert(!R.burst(s));R.advance(s,9);assert(s.burstUntil<s.clockMs);assert(!R.burst(s));R.advance(s,36);assert(R.burst(s));for(let n=2;n<=24;n++)assert(stageConfig(n).bossHp>stageConfig(n-1).bossHp)})
test('five kills grant manual boss eligibility; intro blocks shots; no automatic retry',()=>{const s=R.createInitialState(now);for(let n=0;n<5;n++){s.hp=1;s.manualCooldown=0;assert(R.shoot(s));if(n<4)R.advance(s,.6)}assert.equal(s.kills,5);assert.equal(s.mode,'farm');assert(R.bossReady(s));assert.equal(s.coins,328);assert(R.challenge(s));assert.equal(s.mode,'boss');assert.equal(s.bossIntro,1.8);assert.equal(s.hp,stageConfig(1).bossHp);assert(!R.shoot(s));assert(s.quests.includes('mission-entry-5'));const coins=s.coins;R.advance(s,24);assert.equal(s.mode,'farm');assert.equal(s.cleared,0);assert(s.lastResult.includes('冲到了面前'));R.advance(s,.6);s.hp=1;s.manualCooldown=0;R.shoot(s);assert.equal(s.mode,'farm');assert(s.coins>=coins);assert.equal(s.quests.filter(x=>x==='mission-entry-5').length,1)})
test('locked systems cannot be bypassed; reward and unlock transactions exactly once',()=>{const s=R.createInitialState(now);s.coins=1e9;s.scrap=1e9;assert(!R.upgradeTraining(s));assert(!R.upgradeTactics(s));assert(!R.buyWeapon(s,'revolver'));assert(!R.enhance(s,'glock'));R.selectPanel(s,'skills');assert.equal(s.selectedPanel,'combat');s.kills=5;s.cleared=1;assert(R.upgradeTraining(s));assert(!P.panelUnlocked(s,'market'));s.kills=25;assert(P.panelUnlocked(s,'market'));s.cleared=3;s.kills=299;assert(!R.autoUnlocked(s));s.kills=300;P.resolveMissions(s);assert(R.autoUnlocked(s));const coins=s.coins;P.resolveMissions(s);assert.equal(s.coins,coins);assert.equal(s.quests.filter(x=>x==='mission-kills-300').length,1)})
test('enrage accelerates arrival; burst knocks boss back and handbook sets scale',()=>{const s=R.createInitialState(now);s.cleared=2;s.stage=3;s.kills=60;s.stageKills['3']=stageConfig(3).target;assert(R.challenge(s));R.advance(s,1.9);s.hp=s.maxHp*.3;const before=s.bossTime;R.advance(s,1);assert(Math.abs((before-s.bossTime)-1.35)<1e-7);const time=s.bossTime;assert(R.burst(s));assert.equal(s.bossTime,Math.min(25,time+2));s.kills=650;s.cleared=4;s.fragments=[2,2,2];assert(R.learnManual(s,0));assert.equal(P.manualCost(s,0),2);assert(!R.learnManual(s,0));assert.deepEqual(s.fragments,[1,1,1])})
mkdirSync('artifacts',{recursive:true});writeFileSync('artifacts/domain-checks.json',JSON.stringify({passed:results.length,tests:results},null,2))

test('reference pace: many hits per ordinary enemy; unprepared boss fails and preparation can win',()=>{const fresh=R.createInitialState(now);assert.equal(Math.ceil(fresh.maxHp/R.baseDamage(fresh)),18);R.advance(fresh,1,5);assert.equal(fresh.kills,0);const s=R.createInitialState(now);s.kills=5;s.stageKills['1']=5;assert(P.featureUnlocked(s,'training'));assert(R.challenge(s));R.advance(s,23,5);assert.equal(s.cleared,0);assert.equal(s.mode,'farm');s.coins=10000;while(s.training<8)assert(R.upgradeTraining(s));assert(R.challenge(s));R.advance(s,22,5);assert.equal(s.cleared,1);assert(s.coins>0)})
test('pre-boss growth is reachable: market and enhancement before first clear',()=>{const s=R.createInitialState(now);s.kills=25;s.coins=350;assert(P.panelUnlocked(s,'market'));assert(R.buyWeapon(s,'revolver'));s.proficiency.pistol=25;assert(R.equip(s,'revolver'));s.kills=60;s.scrap=20;assert(R.enhance(s,'revolver'));assert.equal(s.enhancements.revolver,1)})
writeFileSync('artifacts/domain-checks.json',JSON.stringify({passed:results.length,tests:results},null,2))
